version: '3.2'

networks: 
  lan:

services:
  nginx:
      image: nginx:stable-alpine
      container_name: nginx
      ports:
          - "8080:80"
      volumes:
          - ./api/images:/var/www/html
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      networks:
          - lan